// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIVwjcDdJGEhrTzXSnGXv6mxjEXbmwDzA',
    appId: '1:508947228679:web:30d0889b73bca85938e2a2',
    messagingSenderId: '508947228679',
    projectId: 'truckmatemvp',
    authDomain: 'truckmatemvp.firebaseapp.com',
    storageBucket: 'truckmatemvp.firebasestorage.app',
    measurementId: 'G-83JWN98CLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0QSlteehtbxDB1wOugtzwxrI7b1bj4fk',
    appId: '1:508947228679:android:5410c8c8abd876c738e2a2',
    messagingSenderId: '508947228679',
    projectId: 'truckmatemvp',
    storageBucket: 'truckmatemvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTpUylR5PhbyQWWQf5VxEuMQzYEVQXYs0',
    appId: '1:508947228679:ios:f63e35114227515c38e2a2',
    messagingSenderId: '508947228679',
    projectId: 'truckmatemvp',
    storageBucket: 'truckmatemvp.firebasestorage.app',
    androidClientId: '508947228679-7o514equlop3v5m6ur0tfntjo4hbkf6k.apps.googleusercontent.com',
    iosClientId: '508947228679-ebuk1ejl71leigt2hm7rqlopm11t7088.apps.googleusercontent.com',
    iosBundleId: 'com.example.truckmateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTpUylR5PhbyQWWQf5VxEuMQzYEVQXYs0',
    appId: '1:508947228679:ios:f63e35114227515c38e2a2',
    messagingSenderId: '508947228679',
    projectId: 'truckmatemvp',
    storageBucket: 'truckmatemvp.firebasestorage.app',
    androidClientId: '508947228679-7o514equlop3v5m6ur0tfntjo4hbkf6k.apps.googleusercontent.com',
    iosClientId: '508947228679-ebuk1ejl71leigt2hm7rqlopm11t7088.apps.googleusercontent.com',
    iosBundleId: 'com.example.truckmateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIVwjcDdJGEhrTzXSnGXv6mxjEXbmwDzA',
    appId: '1:508947228679:web:06b8289394c7209338e2a2',
    messagingSenderId: '508947228679',
    projectId: 'truckmatemvp',
    authDomain: 'truckmatemvp.firebaseapp.com',
    storageBucket: 'truckmatemvp.firebasestorage.app',
    measurementId: 'G-YQRG12QB96',
  );
}
